version: '3.4'

services:
  shiftfrontend:
    image: Shift/test:1.0
    build:
      context: front_end
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5173:3000
