import { Action, IResourceItem } from "@refinedev/core";

type TitleHandler = {
  resource?: IResourceItem | undefined;
  action?: Action | undefined;
  params?: Record<string, string | undefined> | undefined;
  pathname?: string | undefined;
  autoGeneratedTitle: string;
};

const titleHandler = ({ resource, action, params }: TitleHandler): string => {
  let title = `Shift | ${resource?.meta?.label}`;
  return title;
};

export default titleHandler;
